[build]
  # Build both server and client assets
  command = "npm run build:server && npm run build"
  # Directory containing the built client-side assets
  publish = "client/dist"
  # Directory where Netlify will find the serverless functions
  functions = "netlify/functions"

[functions]
  # Specify the Node.js runtime version if needed (optional, Netlify often defaults reasonably)
  # node_bundler = "esbuild" # Optional: Use esbuild for faster function bundling

[[redirects]]
  # Redirect all API requests to the serverless function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  # Force allows overriding Netlify's default file serving behavior for this path
  force = true

[[redirects]]
  # Fallback for client-side routing (Single Page Application)
  from = "/*"
  to = "/index.html"
  status = 200
[dev]
  # Directory to serve for local development
  publish = "client/dist" # Or "client" if you want Netlify Dev to run the client dev server
  # Command to run for local development (might need adjustment)
  command = "npm --prefix client run dev" # Placeholder - assuming 'npm run dev' starts your client dev server